--
--           ____     __       _         
-- _ __  ___|___ \   / _|_ __ | | ____ _ 
--| '_ \/ __| __) | | |_| '_ \| |/ / _` |
--| |_) \__ \/ __/  |  _| |_) |   < (_| |
--| .__/|___/_____| |_| | .__/|_|\_\__, |
--|_|                   |_|        |___/ 
-- 		  ps2emu Extras Script
--	   generated by PS2-FPKG v0.6
apiRequest(2.0)

local emuObj    = getEmuObject()
local eeObj    = getEEObject()
    
local ThrottleOn = 4
local lightDef = {0,0,255}
local lightThr = {255,0,0}

emuObj.PadSetLightBar(0, lightDef[1], lightDef[2], lightDef[3])

local widescreen = function()
--comment=Widescreen Hack
eeObj.WriteMem32(0x001f34e4,0x3c013f40)

end

local CheckInputs = function()

    local pad_bits = emuObj.GetPad()
    local UP        = pad_bits &  0x0010
    local DOWN        = pad_bits &  0x0040
    local LEFT        = pad_bits &  0x0080
    local RIGHT        = pad_bits &  0x0020
    local Triangle    = pad_bits &  0x1000
    local Cross        = pad_bits &  0x4000
    local Square    = pad_bits &  0x8000
    local Circle    = pad_bits &  0x2000
    local L1        = pad_bits &  0x0400
    local L2        = pad_bits &  0x0100
    local L3        = pad_bits &  0x0002
    local R1        = pad_bits &  0x0800
    local R2        = pad_bits &  0x0200
    local R3        = pad_bits &  0x0004
    local Select    = pad_bits &  0x0001
    local Start        = pad_bits &  0x0008    
    local Nothing = 1

    local onBtn1 = L3
    local onBtn2 = Start
    local onBtn3 = Nothing
    local offBtn1 = L3
    local offBtn2 = Select
    local offBtn3 = Nothing

    widescreen()

    if (onBtn1 ~= 0) and (onBtn2 ~= 0) and (onBtn3 ~= 0) and (ThrottleOn == 0) then
    	emuObj.ThrottleMax()
    	emuObj.PadSetLightBar(0, lightThr[1], lightThr[2], lightThr[3])
    	ThrottleOn = 1
    elseif (offBtn1 ~= 0) and (offBtn2 ~= 0) and (offBtn3 ~= 0) and (ThrottleOn == 1) then
    	emuObj.ThrottleNorm()
    	emuObj.PadSetLightBar(0, lightDef[1], lightDef[2], lightDef[3])
    	ThrottleOn = 0
    end 
    	
    if (ThrottleOn == 3) then
    	if (onBtn1 ~= 0) and (onBtn2 ~= 0) and (onBtn3 ~= 0) then
    		emuObj.ThrottleMax()
    		emuObj.PadSetLightBar(0, lightThr[1], lightThr[2], lightThr[3])
    	else
    		emuObj.ThrottleNorm()
    		emuObj.PadSetLightBar(0, lightDef[1], lightDef[2], lightDef[3])
    	end
    end

end

emuObj.AddVsyncHook(CheckInputs)
    